# Generated by Django 5.0.6 on 2024-07-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='user',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
